# .github/workflows/release.yaml

on:
  release:
    types: [created]

env:
  goversion: $(go mod edit -json | jq -r .Go)

permissions:
    contents: write 
    packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: wangyoucao577/go-release-action@6ac7dba1f9e61850053324549cb6bc88e4b473d2 # v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        goversion: $goversion
        project_path: ./livecraft
        binary_name: livecraft